# Generated by Django 4.0 on 2022-01-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='companys',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='money',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='telegram',
        ),
    ]
