# Generated by Django 4.0 on 2022-01-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_myuser_companys_remove_myuser_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='companys',
            field=models.IntegerField(default=0, verbose_name='Кампании'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='telegram',
            field=models.CharField(default='', max_length=100, verbose_name='Telegram'),
        ),
    ]
