# Generated by Django 4.0 on 2022-01-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='account_type',
            field=models.CharField(choices=[('1', 'Base'), ('2', 'Expert'), ('3', 'Pro')], default='1', max_length=10, verbose_name='Тип аккаунта'),
        ),
    ]
