# Generated by Django 4.0 on 2022-01-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_myuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='account_type',
            field=models.CharField(choices=[('BASE', 'Base'), ('EXPERT', 'Expert'), ('PRO', 'Pro')], default='Base', max_length=10, verbose_name='Тип аккаунта'),
        ),
    ]
