# Generated by Django 4.0 on 2022-01-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='img/avatar/png', upload_to='', verbose_name='Аватар'),
        ),
    ]
