# Generated by Django 4.0 on 2022-01-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_message_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_message',
            field=models.EmailField(default='', max_length=254, verbose_name='Отправитель'),
        ),
    ]
