# Generated by Django 4.0 on 2021-12-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(default=None, upload_to='images', verbose_name='Изображение'),
        ),
    ]
