# Generated by Django 4.0 on 2022-01-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
