# Generated by Django 4.0 on 2022-01-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default='admin@mail.ru', max_length=50, verbose_name='Автор'),
        ),
    ]
