# Generated by Django 4.0 on 2022-01-31 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_useroffers_offer_profit_useroffers_offer_sells_and_more'),
        ('news', '0007_alter_articles_anons_alter_articles_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.myuser'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
    ]
