# Generated by Django 4.0 on 2022-01-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_useroffers_offer_profit_useroffers_offer_sells_and_more'),
        ('news', '0008_alter_articles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.myuser'),
        ),
    ]
